on: 
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
        description: repos/owner
    secrets:
      TOKEN:
        required: true

jobs:
  run:
    runs-on: windows-2019
    strategy:
      matrix:
        config:
        - {python: "3.7", tag: "cp37-cp37m"}
        - {python: "3.8", tag: "cp38-cp38"}
        #- {python: "3.9", tag: "cp39-cp39"}
        #- {python: "3.10", tag: "cp310-cp310"}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.config.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.config.python }}
    - uses: Geode-solutions/actions/get-release@master
      id: repos
      with:
        repository: $(echo ${{ inputs.repos }}| cut -d'/' -f 1)
        owner: $(echo ${{ inputs.repos }}| cut -d'/' -f 2)
        file: 'win64-private.zip'
        token: ${{ secrets.TOKEN }}
    - name: Compile
      run: |
        pip install wheel
        choco install openssl -r --no-progress
        if(!(test-path build)) { mkdir build }
        cd build
        $version = ${env:GITHUB_REF} -replace 'refs\/tags\/v', ''
        echo "::set-output name=version::$version"
        cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH:PATH="${{ steps.repos.outputs.path }}" -D${{ inputs.name }}_WITH_TESTS:BOOL=OFF -DWHEEL_VERSION:STRING=$version -D${{ inputs.name }}_WITH_PYTHON:BOOL=ON -DPYTHON_VERSION:STRING=${{ matrix.config.python }} ..
        cmake --build . --config Release -j 2
        cd ${{ inputs.directory }}
        cmake --build . --target wheel --config Release
    - name: Upload
      uses: geode-solutions/action-gh-release@master
      with:
        files: build/${{ inputs.directory }}/wheel/dist/*.whl
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}