on: 
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      directory:
        type: string
        default: "."
      repos:
        type: string
        description: repos/owner
    secrets:
      TOKEN:
        required: true

jobs:
  run:
    runs-on: windows-2019
    strategy:
      matrix:
        python: ["3.7", "3.8"]
    steps:
    - name: RepoOwner
      id: reposowner
      run: |
        repo_name = $(echo ${{ inputs.repos }}| cut -d'/' -f 1)
        repos_owner = $(echo ${{ inputs.repos }}| cut -d'/' -f 2)
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - uses: Geode-solutions/actions/get-release@master
      id: repos
      with:
        repository: ${{ steps.reposowner.repo_name }}
        owner: ${{ steps.reposowner.repos_owner }}
        file: '-win64-private.zip'
        token: ${{ secrets.TOKEN }}
    - name: Libraries
      id: libraries
      run: |
        $old_path = "${{ steps.repos.outputs.path }}"
        $new_path = $old_path.replace(";", "\bin;")
        echo "::set-output name=path::$new_path"
    - name: Compile & Test
      run: |
        pip install wheel
        choco install openssl -r --no-progress
        if(!(test-path build)) { mkdir build }
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH="${{ steps.repos.outputs.path }}" -D${{ inputs.name }}_WITH_PYTHON:BOOL=ON -DPYTHON_VERSION:STRING=${{ matrix.python }} ..
        cmake --build . --config Debug -j 2
        cd ${{ inputs.directory }}
        $paths = "${{ steps.libraries.outputs.path }}"
        Foreach($path in $paths.split(";")){if(Test-Path -Path $path) {Copy-Item -Path $path\* -Destination bin\Debug}}
        dir bin\Debug
        ctest -V -C Debug --output-on-failure -j 2
        cmake --build . --target wheel --config Debug
      
